module.exports = [
  { name: 'Brasil', path: 'BR', flag: 'assets/brazil.png' },
  { name: 'Acré', path: 'AC', flag: 'assets/1AC.png' },
  { name: 'Alagoas', path: 'AL', flag: 'assets/2AL.png' },
  { name: 'Amapá', path: 'AP', flag: 'assets/3AP.png' },
  { name: 'Amazonas', path: 'AM', flag: 'assets/4AM.png' },
  { name: 'Bahia', path: 'BA', flag: 'assets/5BA.png' },
  { name: 'Ceará', path: 'CE', flag: 'assets/6CE.png' },
  { name: 'Distrito Federal', path: 'DF', flag: 'assets/7DF.png' },
  { name: 'Espírito Santo', path: 'ES', flag: 'assets/8ES.png' },
  { name: 'Goias', path: 'GO', flag: 'assets/9GO.png' },
  { name: 'Maranhão', path: 'MA', flag: 'assets/10MA.png' },
  { name: 'Mato Grosso', path: 'MT', flag: 'assets/11MT.png' },
  { name: 'Mato Grosso do Sul', path: 'MS', flag: 'assets/12MS.png' },
  { name: 'Minas Gerais', path: 'MG', flag: 'assets/13MG.png' },
  { name: 'Paraíba', path: 'PB', flag: 'assets/15PB.png' },
  { name: 'Pará', path: 'PR', flag: 'assets/16PR.png' },
  { name: 'Paraná', path: 'PA', flag: 'assets/14PA.png' },
  { name: 'Pernambuco', path: 'PE', flag: 'assets/17PE.png' },
  { name: 'Piauí', path: 'PI', flag: 'assets/18PI.png' },
  { name: 'Rio de Janeiro', path: 'RJ', flag: 'assets/19RJ.png' },
  { name: 'Rio Grande do Norte', path: 'RN', flag: 'assets/20RN.png' },
  { name: 'Rio Grande do Sul', path: 'RS', flag: 'assets/21RS.png' },
  { name: 'Rondônia', path: 'RO', flag: 'assets/22RO.png' },
  { name: 'Roráima', path: 'RR', flag: 'assets/23RR.png' },
  { name: 'Santa Catarina', path: 'SC', flag: 'assets/24SC.png' },
  { name: 'São Paulo', path: 'SP', flag: 'assets/25SP.png' },
  { name: 'Sergipe', path: 'SE', flag: 'assets/26SE.png' },
  { name: 'Tocantins', path: 'TO', flag: 'assets/27TO.png' },
];
