stages:
  - audit
  - test
  - lint
  - build

audit:
  stage: audit
  image: node:22-alpine
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.0 --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm audit --audit-level=high

test:
  stage: test
  image: node:22-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.0 --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm test:coverage
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage/lcov.info
      - coverage/index.html

lint:
  stage: lint
  image: node:22-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.0 --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm check

build:
  stage: build
  image: node:22-alpine
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.0 --activate
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
