import type { ComponentProps } from "preact/compat";

export type CustomSVGProps = ComponentProps<"svg"> & { size?: number; iconTitle?: string };

const ICON_NAMES = [
	"arrow-left",
	"arrow-right",
	"categories/AllIcon",
	"categories/AlphabetIcon",
	"categories/AnimalsIcon",
	"categories/BodyIcon",
	"categories/CountriesIcon",
	"categories/FamilyIcon",
	"categories/FeelingsIcon",
	"categories/FoodsIcon",
	"categories/FruitsIcon",
	"categories/HealthIcon",
	"categories/JobsIcon",
	"categories/LocationsIcon",
	"categories/MachinesIcon",
	"categories/MeasuresIcon",
	"categories/NatureIcon",
	"categories/NumbersIcon",
	"categories/SportsIcon",
	"categories/UndefinedIcon",
	"categories/VerbsIcon",
	"emotions/angry",
	"emotions/automatic",
	"emotions/default",
	"emotions/disgust",
	"emotions/doubt",
	"emotions/fear",
	"emotions/happy",
	"emotions/sad",
	"emotions/surprise",
	"chevron-down",
	"chevron-left",
	"chevron-up",
	"collapse",
	"comment",
	"dictionary",
	"expand",
	"facebook",
	"govbr",
	"guga",
	"hands",
	"help",
	"hosana",
	"icaro",
	"info",
	"instagram",
	"libras",
	"like",
	"link",
	"menu",
	"pause",
	"play",
	"repeat",
	"rotate-left",
	"settings",
	"skip",
	"subtitle-off",
	"subtitle",
	"thumbs-down",
	"thumbs-up",
	"touch",
	"translator",
	"trash",
	"twitter",
	"waiting",
	"worldwide",
	"x",
	"youtube",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
