import type { ComponentProps } from "preact/compat";

export type CustomSVGProps = ComponentProps<"svg"> & { size?: number; iconTitle?: string };

const ICON_NAMES = [
	"arrow-left",
	"arrow-right",
	"categories-icons/AllIcon",
	"categories-icons/AlphabetIcon",
	"categories-icons/AnimalsIcon",
	"categories-icons/BodyIcon",
	"categories-icons/CountriesIcon",
	"categories-icons/FamilyIcon",
	"categories-icons/FeelingsIcon",
	"categories-icons/FoodsIcon",
	"categories-icons/FruitsIcon",
	"categories-icons/HealthIcon",
	"categories-icons/JobsIcon",
	"categories-icons/LocationsIcon",
	"categories-icons/MachinesIcon",
	"categories-icons/MeasuresIcon",
	"categories-icons/NatureIcon",
	"categories-icons/NumbersIcon",
	"categories-icons/SportsIcon",
	"categories-icons/UndefinedIcon",
	"categories-icons/VerbsIcon",
	"chevron-down",
	"chevron-left-icon",
	"chevron-up",
	"collapse",
	"comment",
	"dictionary",
	"emotions-icons/angry",
	"emotions-icons/automatic",
	"emotions-icons/default",
	"emotions-icons/disgust",
	"emotions-icons/doubt",
	"emotions-icons/fear",
	"emotions-icons/happy",
	"emotions-icons/sad",
	"emotions-icons/surprise",
	"expand",
	"facebook",
	"govbr",
	"guga",
	"hands",
	"help",
	"hosana",
	"icaro",
	"info",
	"instagram",
	"libras",
	"like",
	"link",
	"menu",
	"pause",
	"play",
	"repeat",
	"rotate-left",
	"settings",
	"skip",
	"subtitle-off",
	"subtitle",
	"thumbs-down",
	"thumbs-up",
	"touch",
	"translator",
	"trash",
	"twitter",
	"waiting",
	"worldwide",
	"x",
	"youtube",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
