import type { ComponentProps } from "preact/compat";

export type CustomSVGProps = ComponentProps<"svg"> & { size?: number; iconTitle?: string };

const ICON_NAMES = [
	"arrow-left",
	"arrow-right",
	"categories/all",
	"categories/alphabet",
	"categories/animals",
	"categories/body",
	"categories/countries",
	"categories/family",
	"categories/feelings",
	"categories/foods",
	"categories/fruits",
	"categories/health",
	"categories/jobs",
	"categories/locations",
	"categories/machines",
	"categories/measures",
	"categories/nature",
	"categories/numbers",
	"categories/sports",
	"categories/undefined",
	"categories/verbs",
	"emotions/angry",
	"emotions/automatic",
	"emotions/default",
	"emotions/disgust",
	"emotions/doubt",
	"emotions/fear",
	"emotions/happy",
	"emotions/sad",
	"emotions/surprise",
	"chevron-down",
	"chevron-left",
	"chevron-up",
	"collapse",
	"comment",
	"dictionary",
	"expand",
	"facebook",
	"govbr",
	"guga",
	"hands",
	"help",
	"hosana",
	"icaro",
	"info",
	"instagram",
	"libras",
	"like",
	"link",
	"menu",
	"pause",
	"play",
	"repeat",
	"rotate-left",
	"settings",
	"skip",
	"subtitle-off",
	"subtitle",
	"thumbs-down",
	"thumbs-up",
	"touch",
	"translator",
	"trash",
	"twitter",
	"waiting",
	"worldwide",
	"x",
	"youtube",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
